name: mvvm_service
description: A Flutter-native service layer inspired by the MVVM pattern, managing services according to the widget lifecycle, without relying on Provider or Riverpod.
version: 1.1.1
publisher: ttankkeo112@gmail.com
repository: https://github.com/flutter-service/service
keywords:
  - flutter
  - service
  - mvvm
  - state-management
  - flutter-architecture
  - riverpod-free
  - async-data

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
